In [78]:
import pandas as pd

risk_label_map = {
    0: 0, # high risk
    1: 1, # medium risk
    2: 1, # medium risk
    3: 2 # low risk
}

project_name = "stad"

origianal_text_anchor_structured = pd.read_csv("/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/data/diagnostic_description_musk.csv")
original_text_anchor_long_context = pd.read_csv("/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/data/diagnostic_description_bert.csv")
text_reports_structrued = pd.read_csv("/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/data/structured_reports_llama.csv").loc[:, ["patient_id", "structured_report_musk"]]
text_reports_long_context = pd.read_csv("/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/data/long_context_summarized_report_llama.csv").loc[:, ["patient_id", "long_context_summarization"]]
df_meta = pd.read_csv(f"/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/data/OS/tcga_{project_name}_all.csv")
df_meta.label = df_meta.label.map(lambda x: risk_label_map[x])
df_meta

,case_id,slide_id,survival_months,censorship,label
0,TCGA-3M-AB46,TCGA-3M-AB46-01Z-00-DX1.svs,57.98,1,2
1,TCGA-B7-5816,TCGA-B7-5816-01Z-00-DX1.svs,26.68,1,2
2,TCGA-BR-6452,TCGA-BR-6452-01Z-00-DX1.svs,34.66,1,2
3,TCGA-BR-6453,TCGA-BR-6453-01Z-00-DX1.svs,15.93,1,1
4,TCGA-BR-6455,TCGA-BR-6455-01Z-00-DX1.svs,13.86,0,1
...,...,...,...,...,...
344,TCGA-VQ-AA6I,TCGA-VQ-AA6I-01Z-00-DX1.svs,16.13,0,1
345,TCGA-VQ-AA6J,TCGA-VQ-AA6J-01Z-00-DX1.svs,27.53,1,2
346,TCGA-VQ-AA6K,TCGA-VQ-AA6K-01Z-00-DX1.svs,12.42,0,1
347,TCGA-ZA-A8F6,TCGA-ZA-A8F6-01Z-00-DX1.svs,17.25,1,1
348,TCGA-ZQ-A9CR,TCGA-ZQ-A9CR-01Z-00-DX1.svs,0.79,0,0

In [79]:
sampled_df = df_meta[df_meta.censorship == 0].sample(frac=1.0, random_state=42).groupby("label").head(5).sort_values("label")
# sampled_df = df_meta.sample(frac=1.0, random_state=42).groupby("label").head(50).sort_values("label")
sampled_df = sampled_df.merge(text_reports_structrued, left_on="case_id", right_on="patient_id", how="left").dropna().groupby("label").head(3)
sampled_df = sampled_df.merge(text_reports_long_context, left_on="case_id", right_on="patient_id", how="left").drop(["patient_id_x", "patient_id_y"], axis=1)
sampled_df

,case_id,slide_id,survival_months,censorship,label,structured_report_musk,long_context_summarization
0,TCGA-BR-7901,TCGA-BR-7901-01Z-00-DX1.svs,3.45,0,0,The tumor at the gastroesophageal junction mea...,The cancer is an adenocarcinoma of the gastroe...
1,TCGA-VQ-A94P,TCGA-VQ-A94P-01Z-00-DX1.svs,2.66,0,0,The tumor in the stomach body measures 4.0 cm ...,The cancer is an adenocarcinoma of the stomach...
2,TCGA-BR-A4CS,TCGA-BR-A4CS-01Z-00-DX1.svs,1.48,0,0,The tumor in the stomach fundus measures 5 x 4...,The cancer is an adenocarcinoma of the stomach...
3,TCGA-VQ-A8PD,TCGA-VQ-A8PD-01Z-00-DX1.svs,16.29,0,1,The tumor in the stomach measures 8.7 x 6.5 cm...,The cancer is a moderately differentiated aden...
4,TCGA-D7-6527,TCGA-D7-6527-01Z-00-DX1.svs,10.25,0,1,The tumor in the stomach's cardiac region meas...,The cancer is a papillary adenocarcinoma of th...
5,TCGA-VQ-A91D,TCGA-VQ-A91D-01Z-00-DX1.svs,11.70,0,1,The tumor in the stomach measures 5.0x4.5x4.0 ...,The cancer is an invasive ulcerated moderately...
6,TCGA-BR-8686,TCGA-BR-8686-01Z-00-DX1.svs,20.86,0,2,The tumor in the stomach measures 10 x 8 x 3 c...,The cancer is a poorly differentiated tubular ...
7,TCGA-HJ-7597,TCGA-HJ-7597-01Z-00-DX1.svs,26.45,0,2,The tumor in the stomach has a most significan...,The cancer is an invasive adenocarcinoma of th...
8,TCGA-VQ-A8E3,TCGA-VQ-A8E3-01Z-00-DX1.svs,21.71,0,2,The tumor in the stomach's antrum measures 7.5...,The cancer is a poorly differentiated adenocar...

In [80]:
# for fold in range(5):
#     fold_df = pd.read_csv(f"/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/splits/OS/tcga_{project_name}/splits_{fold}.csv")
    
#     train_ids = fold_df.train[~fold_df.train.isin(sampled_df.case_id.tolist())].tolist()
#     val_ids = fold_df.val[~fold_df.val.isin(sampled_df.case_id.tolist())].dropna().tolist()
    
#     new_fold_df = pd.DataFrame({
#         "train": train_ids,
#         "val": val_ids + [None] * (len(train_ids) - len(val_ids))
#     })
    
#     new_fold_df.to_csv(f"/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM_VLM_refined_anchor/splits/OS/tcga_{project_name}/refined_splits_{fold}.csv", index=False)

In [81]:
low_risk_descriptions = sampled_df[sampled_df.label == 2].structured_report_musk.tolist()
intermediate_risk_descriptions = sampled_df[sampled_df.label == 1].structured_report_musk.tolist()
high_risk_descriptions = sampled_df[sampled_df.label == 0].structured_report_musk.tolist()

low_risk_anchor = origianal_text_anchor_structured.loc[origianal_text_anchor_structured.project == project_name.upper(), "low_risk"].values[0]
intermediate_risk_anchor = origianal_text_anchor_structured.loc[origianal_text_anchor_structured.project == project_name.upper(), "intermediate_risk"].values[0]
high_risk_anchor = origianal_text_anchor_structured.loc[origianal_text_anchor_structured.project == project_name.upper(), "high_risk"].values[0]

In [82]:
print(f"""
You are a clinical pathology writing assistant. Your task is to REWRITE the risk anchors so that each anchor (Low / Intermediate / High) **generalizes across** the provided patient reports while remaining clinically faithful.

### Inputs for {project_name.upper()}
1) Current anchor drafts:
- Low-risk (draft):
{low_risk_anchor}

- Intermediate-risk (draft):
{intermediate_risk_anchor}

- High-risk (draft):
{high_risk_anchor}

2) Patient reports to align with:
- Low-risk examples:
• {low_risk_descriptions[0]}
• {low_risk_descriptions[1]}
• {low_risk_descriptions[2]}

- Intermediate-risk examples:
• {intermediate_risk_descriptions[0]}
• {intermediate_risk_descriptions[1]}
• {intermediate_risk_descriptions[2]}

- High-risk examples:
• {high_risk_descriptions[0]}
• {high_risk_descriptions[1]}
• {high_risk_descriptions[2]}

### What to do
- Start from the current drafts but **refine** them to cover the common patterns across the example reports.
- Prioritize **risk-defining axes** over raw size: differentiation/grade, depth and extent of invasion (organ-wall layers, fat/sinus/peritoneum/adjacent organs), lymph node status (including NX), margin status (especially vascular/soft-tissue margins), and vascular/perineural invasion. Mention size qualitatively only if helpful (e.g., “small/moderate/large”), avoid exact measurements.
- If the disease/site can be inferred from the reports, use **site-appropriate anatomy terms** (e.g., pericolonic fat / renal sinus / perinephric fat). If uncertain, use neutral terms (“adjacent soft tissue”, “regional nodes”).
- **Do not copy** sentences verbatim from the reports. **Abstract and paraphrase**; prefer clinically neutral, guideline-like wording.
- Capture heterogeneity with inclusive phrasing (“confined to … or focal involvement of … without frank invasion of …”; “nodes negative when assessed; NX acceptable”).
- Keep each anchor concise: **2–3 sentences**, **≤ 90 words** per risk.
- **No JSON, no lists, no meta commentary.** Output plain prose only.

### Output format (plain text, exactly this order)
Low-Risk Anchor:
<one short paragraph>

Intermediate-Risk Anchor:
<one short paragraph>

High-Risk Anchor:
<one short paragraph>
""")

You are a clinical pathology writing assistant. Your task is to REWRITE the risk anchors so that each anchor (Low / Intermediate / High) **generalizes across** the provided patient reports while remaining clinically faithful.

### Inputs for STAD
1) Current anchor drafts:
- Low-risk (draft):
The gastric carcinoma is generally confined to the mucosa, submucosa, or superficial muscularis propria without frank penetration through the full gastric wall or direct involvement of adjacent organs. Tumors may be well to poorly differentiated, but regional lymph nodes are negative when assessed, and margins are uninvolved, consistent with complete resection. Vascular or perineural invasion is absent or limited, and residual disease is not identified.

- Intermediate-risk (draft):
The gastric tumor demonstrates deeper invasion through the muscularis propria into perigastric fat or serosal surfaces, but without extensive extension into adjacent organs. Differentiation is usually moderate to poor, and angiolymphatic or perineural invasion may be present. Regional lymph node metastasis is limited, typically involving a small subset of examined nodes, while surgical margins are free of disease or only focally close.

- High-risk (draft):
The gastric carcinoma shows advanced local disease with poorly differentiated features and widespread atypia. There is clear invasion through the full thickness of the gastric wall into peritoneum, omentum, or adjacent organs. Lymph node metastasis is common and often involves multiple nodes. Surgical margins may be close or involved, and vascular or perineural invasion is frequently present, indicating aggressive and advanced disease.

2) Patient reports to align with:
- Low-risk examples:
• The tumor in the stomach measures 10 x 8 x 3 cm and is a poorly differentiated tubular adenocarcinoma. The tumor is invading the serosa (visceral peritoneum). There is evidence of lymph node metastasis with 2 out of 2 lymph nodes positive for metastasis. Lymphatic invasion is also present. The margins are not specified in the report.
• The tumor in the stomach has a most significant dimension of 6.5 cm (6.5 x 5.5 x 2.0 cm) and is a poorly differentiated adenocarcinoma with a signet ring cell component. The tumor invades into the subserosa, and the invasive carcinoma is <0.1 cm from the serosal surface, indicating close proximity to adjacent tissues. There is no evidence of lymph node metastasis in 37 lymph nodes examined. The
• The tumor in the stomach's antrum measures 7.5 cm and is a poorly differentiated adenocarcinoma. The lesion shows angiolymphatic invasion and infiltrates the subserosal adipose tissue, indicating invasion of adjacent tissues. There is no evidence of lymph node metastasis, with 0 out of 20 lymph nodes involved. The margins of the excised tissue are clear of disease, with surgical margins uninvolved by neoplasia, and other tissues such

- Intermediate-risk examples:
• The tumor in the stomach measures 8.7 x 6.5 cm and is a moderately differentiated adenocarcinoma. The lesion infiltrates the segment wall until the adipose perigastric tissue. There is evidence of the lesion invading adjacent tissues, including angiolymphatic invasion and perineural invasion. Lymph node metastasis is present in multiple nodes, including 13/13 in the small curvature and 6/6 in the greater curvature. The margins of the
• The tumor in the stomach's cardiac region measures 5.2 x 4.1 x 0.4 cm with an ulceration of 4.6 x 3.8 cm. The lesion is moderately differentiated (G2). There is evidence of the lesion invading the muscularis propria of the stomach and the esophageal wall, and cancerous emboli are present in the vessels. Metastatic carcinoma was found in regional lymph nodes (No I/XIV). The margins
• The tumor in the stomach measures 5.0x4.5x4.0 cm. It is moderately differentiated, with Lauren's intestinal type adenocarcinoma. The lesion invades adjacent tissues, including the serosa, fat tissue, omentum, and colon. There is evidence of lymph node metastasis, with 5 out of 33 examined perigastric lymph nodes involved by neoplasia. The margins of the excised tissue, including the stomach and

- High-risk examples:
• The tumor at the gastroesophageal junction measures 8 x 6 cm. Moderately differentiated; The tumor shows invasion into the subserosa, perigastric fat, and adjacent fatty tissue, and spreads into the esophagus; Two out of 15 lymph nodes examined demonstrate metastases; The margins of the excised tissue, including the omentum, are uninvolved by tumor, indicating a negative surgical margin status.
• The tumor in the stomach body measures 4.0 cm along its longest axis. It is poorly differentiated, with a histologic grade of III. The tumor shows compromise of the serosa and neural infiltration, with lymphatic vascular invasion, indicating invasion into adjacent tissues. There is evidence of lymph node metastasis, with 5 out of 13 dissected nodes compromised (4 from the greater curvature and 2 from the lesser curvature). The proximal and distal margins of the excised tissue
• The tumor in the stomach fundus measures 5 x 4 x 1.5 cm. The lesion is poorly differentiated adenocarcinoma. There is evidence of the lesion invading the greater omentum. Lymph node metastasis is present, with 7 out of 15 lymph nodes showing metastatic disease. The margins of the excised tissue are uninvolved by disease, indicating a negative surgical margin status.

### What to do
- Start from the current drafts but **refine** them to cover the common patterns across the example reports.
- Prioritize **risk-defining axes** over raw size: differentiation/grade, depth and extent of invasion (organ-wall layers, fat/sinus/peritoneum/adjacent organs), lymph node status (including NX), margin status (especially vascular/soft-tissue margins), and vascular/perineural invasion. Mention size qualitatively only if helpful (e.g., “small/moderate/large”), avoid exact measurements.
- If the disease/site can be inferred from the reports, use **site-appropriate anatomy terms** (e.g., pericolonic fat / renal sinus / perinephric fat). If uncertain, use neutral terms (“adjacent soft tissue”, “regional nodes”).
- **Do not copy** sentences verbatim from the reports. **Abstract and paraphrase**; prefer clinically neutral, guideline-like wording.
- Capture heterogeneity with inclusive phrasing (“confined to … or focal involvement of … without frank invasion of …”; “nodes negative when assessed; NX acceptable”).
- Keep each anchor concise: **2–3 sentences**, **≤ 90 words** per risk.
- **No JSON, no lists, no meta commentary.** Output plain prose only.

### Output format (plain text, exactly this order)
Low-Risk Anchor:
<one short paragraph>

Intermediate-Risk Anchor:
<one short paragraph>

High-Risk Anchor:
<one short paragraph>

In [83]:
low_risk_descriptions = sampled_df[sampled_df.label == 2].long_context_summarization.tolist()
intermediate_risk_descriptions = sampled_df[sampled_df.label == 1].long_context_summarization.tolist()
high_risk_descriptions = sampled_df[sampled_df.label == 0].long_context_summarization.tolist()

low_risk_anchor = original_text_anchor_long_context.loc[original_text_anchor_long_context.project == project_name.upper(), "low_risk"].values[0]
intermediate_risk_anchor = original_text_anchor_long_context.loc[original_text_anchor_long_context.project == project_name.upper(), "intermediate_risk"].values[0]
high_risk_anchor = original_text_anchor_long_context.loc[original_text_anchor_long_context.project == project_name.upper(), "high_risk"].values[0]

In [84]:
print(f"""
You are a clinical pathology writing assistant. Your task is to REWRITE the risk anchors so that each anchor (Low / Intermediate / High) **generalizes across** the provided patient reports while remaining clinically faithful.

### Inputs for {project_name.upper()}
1) Current anchor drafts:
- Low-risk (draft):
{low_risk_anchor}

- Intermediate-risk (draft):
{intermediate_risk_anchor}

- High-risk (draft):
{high_risk_anchor}

2) Patient reports to align with:
- Low-risk examples:
• {low_risk_descriptions[0]}
• {low_risk_descriptions[1]}
• {low_risk_descriptions[2]}

- Intermediate-risk examples:
• {intermediate_risk_descriptions[0]}
• {intermediate_risk_descriptions[1]}
• {intermediate_risk_descriptions[2]}

- High-risk examples:
• {high_risk_descriptions[0]}
• {high_risk_descriptions[1]}
• {high_risk_descriptions[2]}

### What to do
- Start from the current drafts but **refine** them to cover the common patterns across the example reports.
- Prioritize **risk-defining axes** over raw size: differentiation/grade, depth and extent of invasion (organ-wall layers, fat/sinus/peritoneum/adjacent organs), lymph node status (including NX), margin status (especially vascular/soft-tissue margins), and vascular/perineural invasion. Mention size qualitatively only if helpful (e.g., “small/moderate/large”), avoid exact measurements.
- If the disease/site can be inferred from the reports, use **site-appropriate anatomy terms** (e.g., pericolonic fat / renal sinus / perinephric fat). If uncertain, use neutral terms (“adjacent soft tissue”, “regional nodes”).
- **Do not copy** sentences verbatim from the reports. **Abstract and paraphrase**; prefer clinically neutral, guideline-like wording.
- Capture heterogeneity with inclusive phrasing (“confined to … or focal involvement of … without frank invasion of …”; “nodes negative when assessed; NX acceptable”).
- Keep each anchor concise: **5-10 sentences**, **≤ 500 words** per risk.
- **No JSON, no lists, no meta commentary.** Output plain prose only.

### Output format (plain text, exactly this order)
Low-Risk Anchor:
<one short paragraph>

Intermediate-Risk Anchor:
<one short paragraph>

High-Risk Anchor:
<one short paragraph>
""")

You are a clinical pathology writing assistant. Your task is to REWRITE the risk anchors so that each anchor (Low / Intermediate / High) **generalizes across** the provided patient reports while remaining clinically faithful.

### Inputs for STAD
1) Current anchor drafts:
- Low-risk (draft):
Gastric adenocarcinoma at this stage is generally limited in extent, often well to moderately differentiated, though high-grade histology may occasionally be present. Invasion is confined to the mucosa, submucosa, or subserosal adipose tissue without frank penetration of adjacent organs. Regional lymph nodes are negative when sampled, or lymph node status is not reported. Surgical margins are uninvolved, and distant metastasis is absent. Vascular or perineural invasion may be absent or focal, but overall disease remains localized and surgically controlled.

- Intermediate-risk (draft):
The gastric tumor shows moderately to poorly differentiated morphology with more extensive invasion into the muscularis propria, perigastric fat, or serosal surface, but without diffuse adjacent organ involvement. Regional lymph node metastasis is present, often limited in number, with or without focal extracapsular extension. Lymphovascular and/or perineural invasion is frequently identified. Margins are typically negative, and no distant metastasis is documented. This profile represents locally advanced but still surgically resected disease with a moderate nodal burden.

- High-risk (draft):
High-risk gastric adenocarcinoma is characterized by poorly differentiated or aggressive morphology, with marked atypia, brisk mitotic activity, and frequent necrosis. Tumors extend through the gastric wall with invasion into adjacent organs or peritoneal structures, or they demonstrate extensive nodal involvement with multiple positive regional nodes, often with extracapsular extension. Surgical margins may be close or positive, and distant metastasis may be present. These findings indicate advanced, aggressive disease with high risk of recurrence and systemic spread.

2) Patient reports to align with:
- Low-risk examples:
• The cancer is a poorly differentiated tubular adenocarcinoma of the stomach, specifically in the antrum; the tumor measures 10 × 8 × 3 cm. It is poorly differentiated. The tumor invades into the serosa (visceral peritoneum) but does not specify invasion into adjacent organs. Lymphatic invasion is present, while venous and perineural invasion are not specified. Surgical margins are not specified. Two lymph nodes are examined, with 2 positive for metastasis. Extracapsular extension is not reported. Distant metastasis is not described. The pathological AJCC stage is not fully reported (T3 or T4 for serosal invasion, but N and M categories not fully detailed). No biomarkers or molecular tests are mentioned. Mitotic activity is described as present with hyperchromatic and irregularly enlarged nuclei and prominent nucleoli. No treatment effect or regression score is mentioned. Additional findings include prominent lymphocytes in the stroma.
• The cancer is an invasive adenocarcinoma of the stomach, poorly differentiated, with a signet ring cell component. The tumor measures 6.5 cm in greatest dimension, 5.5 x 2.0 cm in additional dimensions, and is ulcerated. It invades into the subserosa and is <0.1 cm from the serosal surface. The proximal, distal, and radial margins are negative for tumor, with the invasive tumor being 3.0 cm from the proximal margin (closest margin). Angiolymphatic and perineural invasion are present. Thirty-seven lymph nodes were examined, with none positive for metastasis (0/37). Extracapsular extension is not reported. No distant metastasis is described. The pathological AJCC stage is pT2b N0 MX. No biomarkers or molecular tests are mentioned. The non-neoplastic stomach shows intestinal metaplasia.
• The cancer is a poorly differentiated adenocarcinoma of the stomach (antrum), intestinal pattern of Lauren; the tumor measures 7.5 cm. It is poorly differentiated; the exact histologic differentiation grade is not specified, but described as poorly differentiated. The tumor invades into the subserosal adipose tissue; no specific adjacent organs are mentioned as invaded. There is evidence of angiolymphatic invasion, but no perineural invasion. The surgical margins are uninvolved by neoplasia. A total of 20 lymph nodes were examined (lesser curvature 10, greater curvature 6, and 4 from other stations), and none are positive for metastasis (0/20). Extracapsular extension is not reported. No distant metastasis is described. The pathological AJCC stage is pT3 pN0; M not reported. No biomarkers or molecular tests are mentioned. Mitotic activity and proliferative indices are not described. Low-grade epithelial dysplasia and intestinal metaplasia are noted in adjacent mucosa.

- Intermediate-risk examples:
• The cancer is a moderately differentiated adenocarcinoma of the stomach (body), extending from the esophagogastric junction to the duodenum, measuring 8.7 x 6.5 cm; the histologic differentiation grade is moderately differentiated. The tumor invades the segment wall until the adipose perigastric tissue. Invasion into adjacent tissues, organs, or specific structures is present, specifically into the adipose perigastric tissue; angiolymphatic invasion is also present. Features of lymphovascular invasion (LVI) and perineural invasion (PNI) are both present. The surgical margins are uninvolved by neoplasia, specifically the esophageal margin. A total of 28 lymph nodes were examined, with 25 positive for metastasis (1/1 in "12a", 5/6 in "8a", 13/13 in small curvature, 6/6 in greater curvature, and 1/2 in "11p"). Extracapsular extension is not reported. There is no evidence of distant metastasis. The pathological AJCC stage is pT3 pN3b; M category is not stated. No immunohistochemistry or biomarker results, molecular test results, mitotic activity, necrosis, or proliferative indices are reported. There is no mention of treatment effect or regression score; additional findings include a congested non-neoplastic segment of the stomach, an uninvolved omentum segment, and a congested spleen.
• The cancer is a papillary adenocarcinoma of the stomach, specifically in the cardiac region; the tumor measures 5.2 × 4.1 × 0.4 cm with an ulceration of 4.6 × 3.8 cm. It is moderately differentiated (grade 2, G2). The carcinoma invades into the deep muscle layer of the stomach and esophageal wall, with evidence of lymphovascular invasion (carcinomatous emboli in vessels). The surgical margins are free of tumor. Features of lymphovascular invasion are present (carcinomatous emboli in vessels), but perineural invasion is not described. The surgical margins are free of neoplastic lesions. Four lymph node stations (periorificial, lesser curvature, greater curvature, peripyloric) were examined, with one station showing metastasis (1/4, specifically in lymph node No I/IV, with capsular infiltration). Extracapsular extension is reported in the lymph node metastases (infiltratio carcinomatosa capsulae lymphonodi). No distant metastasis is described. The pathological AJCC stage is pT2 pN1. No biomarkers or molecular tests are mentioned. Chronic inactive gastritis with intestinal metaplasia is noted in the adjacent mucosa.
• The cancer is an invasive ulcerated moderately differentiated adenocarcinoma of the stomach, intestinal type (Lauren classification), grade 2. The tumor measures 5.0 × 4.5 × 4.0 cm. It invades into the serosa and adjacent fat tissue, with involvement of the omentum and colon. Lymphovascular invasion and perineural invasion are present. Surgical margins, including the stomach and colon, are uninvolved by neoplasia. Thirty-three perigastric lymph nodes were examined, with five positive for metastasis (5/33), and extracapsular extension is present with capsular invasion. No distant metastasis is described. The pathological AJCC stage is pT4 pN2; M not reported. No biomarkers or molecular tests are mentioned. Additional findings include inactive discrete chronic gastritis in the adjacent mucosa.

- High-risk examples:
• The cancer is an adenocarcinoma of the gastroesophageal junction; the tumor measures 8 × 6 × 0 cm and is moderately differentiated (G2). It invades into the subserosa and adjacent fatty tissue, and also spreads to the esophagus and adjacent lymph nodes. There is no evidence of lymphatic or venous invasion, and perineural invasion is not specified. The surgical margins, including omentum, are tumor-free. Fifteen lymph nodes were examined, and two are positive for metastasis. There is no mention of distant metastasis. The pathological AJCC stage is not explicitly stated, but can be inferred as pT3 pN1; M not reported. No biomarkers or molecular tests are mentioned. Mitotic activity, necrosis, and proliferative indices are not described. There is no mention of treatment effect or regression score, but evidence of neo-adjuvant treatment is not specified. Additional findings are not specified, but the tumor is described as ulcerated.
• The cancer is an adenocarcinoma of the stomach (body and antrum), poorly differentiated (grade III), with a mucosecreting mucocellular histologic pattern and "signet ring" cells; the tumor measures 4.0 cm in its longest axis. It invades the serosa, with a spiculated type of invasion and moderate inflammatory reaction. There is evidence of neural infiltration and lymphatic vascular invasion, but not sanguineous vascular invasion. The surgical margins, including proximal and distal, are free of neoplastic involvement. 13 lymph nodes were examined, with 5 positive for metastasis (5/13), including 4/11 from the greater curvature and 2/2 from the lesser curvature. Extracapsular extension is not reported. There is no mention of distant metastasis. The pathological AJCC stage is not explicitly stated. Relevant immunohistochemistry or biomarker results are not reported. Molecular test results are not mentioned. Mitotic activity and necrosis are not described, but there is a mention of moderate chronic gastritis with intestinal metaplasia. There is no mention of treatment effect or regression score. Additional findings include moderate chronic gastritis with intestinal metaplasia, and the greater and lesser omentum are free of neoplastic involvement.
• The cancer is an adenocarcinoma of the stomach, specifically in the fundus, poorly differentiated; the tumor measures 5 × 4 × 1.5 cm. The histologic differentiation grade is poorly differentiated. The tumor invades into the greater omentum; there is no information on invasion into other adjacent tissues or organs. Lymphovascular invasion (LVI) and perineural invasion (PNI) are not described. The surgical margins are uninvolved. Seven out of 15 lymph nodes examined are positive for metastasis, all located intraabdominally. Extracapsular extension in lymph node metastases is not reported. There is no evidence of distant metastasis described in the report. The pathological AJCC stage is not fully stated, but it includes at least pT3 due to the invasion into the greater omentum and pN2 given the 7 positive lymph nodes out of 15 examined; the M category is not mentioned. Relevant immunohistochemistry or biomarker results, molecular test results, mitotic activity, necrosis, or proliferative indices are not reported. There is no mention of treatment effect, regression score, or therapy response. No other clinically relevant remarks are provided.

### What to do
- Start from the current drafts but **refine** them to cover the common patterns across the example reports.
- Prioritize **risk-defining axes** over raw size: differentiation/grade, depth and extent of invasion (organ-wall layers, fat/sinus/peritoneum/adjacent organs), lymph node status (including NX), margin status (especially vascular/soft-tissue margins), and vascular/perineural invasion. Mention size qualitatively only if helpful (e.g., “small/moderate/large”), avoid exact measurements.
- If the disease/site can be inferred from the reports, use **site-appropriate anatomy terms** (e.g., pericolonic fat / renal sinus / perinephric fat). If uncertain, use neutral terms (“adjacent soft tissue”, “regional nodes”).
- **Do not copy** sentences verbatim from the reports. **Abstract and paraphrase**; prefer clinically neutral, guideline-like wording.
- Capture heterogeneity with inclusive phrasing (“confined to … or focal involvement of … without frank invasion of …”; “nodes negative when assessed; NX acceptable”).
- Keep each anchor concise: **5-10 sentences**, **≤ 500 words** per risk.
- **No JSON, no lists, no meta commentary.** Output plain prose only.

### Output format (plain text, exactly this order)
Low-Risk Anchor:
<one short paragraph>

Intermediate-Risk Anchor:
<one short paragraph>

High-Risk Anchor:
<one short paragraph>